project:
  type: website

website:
  title: "Introduction_to_Linux"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 00-intro.qmd
        text: Introduction
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

